### ISSUE TITLE
Splitting into multiple packages?

### ISSUE THREAD

**Issue by tavoyne** [gajus/eslint-config-canonical#38]
What about splitting this package into multiple packages (e.g. `eslint-config-canonical-base`, `eslint-config-canonical-react`, etc.), each one with its own dependencies? 

The problem is that in most cases, only a subset of the dependencies will be used per project. Like even if I don't use Typescript in my app, now I'm downloading `@typescript-eslint/parser` along with this library, which is bad for memory, bad for CI, and also makes yarn complaining about unmet peer dependencies (see below).

![image](https://user-images.githubusercontent.com/29731597/146900402-e11e1977-fd10-4e77-9d7a-035a61f939cf.png)

**Comment by gajus** [comment]
Slitting it would defeat the purpose of keeping it a single config. The #1 complaint I hear from people migrating from Prettier to ESLint is that they need to download multiple configs, etc. They like Canonical because it is all wrapped in a single file.

One alternative that I thought of is that we could move all plugins as dependencies of `eslint-plugin-canonical`. Then you would not get those peer dependency warnings.

**Comment by theoavoyne** [comment]
I agree that having everything in a single config makes things easier, particularly for adoption.

The alternative you suggest seems a good option to me.

But, TBH, I still prefer the idea of the package being splitted. It feels more natural. I think the slight increase in simplicity doesn't compensate for having to download a lot of dependencies which, mostly, will end up never being used.

**Comment by theoavoyne** [comment]
In the end, the difference in terms of DX would be negligible.

Instead of:
```sh
yarn install eslint-config-canonical
```

You would do, for example:
```sh
yarn install eslint-config-canonical eslint-config-canonical-node eslint-config-canonical-typescript 
```
(Dependencies would align nicely in `package.json`).

And:
```javascript
/* .eslintrc.js */

{
  "extends": [
    "canonical",
    "canonical-node",
    "canonical-typescript",
  ],
}
```

**Comment by gajus** [comment]
The whole point of canonical is to have all rules in one versioned package. Splitting them into multiple packages would defeat the purpose of a single ruleset to rule them all.

Open to documentation how to improve logs for yargs.

**Comment by sotnikov-link** [comment]
I use .yarnrc.yml for yarn 2+ as work around

```yaml
packageExtensions:
  # Bellow dependencies of eslint-config-canonical
  eslint-config-canonical@*:
    peerDependenciesMeta:
      '@babel/plugin-syntax-flow': { optional: true }
      '@babel/plugin-transform-react-jsx': { optional: true }
      graphql: { optional: true }
      typescript: { optional: true }
      vitest: { optional: true }
  eslint-plugin-canonical@*:
    peerDependenciesMeta:
      eslint: { optional: true }
      typescript: { optional: true }
      eslint-plugin-import: { optional: true }
  '@graphql-tools/graphql-tag-pluck@*':
    peerDependenciesMeta:
      '@babel/core': { optional: true }
```
