### ISSUE TITLE
how to disable semicolons?

### ISSUE THREAD

**Issue by scarf005** [gajus/eslint-config-canonical#61]
## .prettierrc.yml
```yml
semi: false
```
## .eslintrc.yml
```yaml
root: true
env:
  browser: true
  es2021: true

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module

extends:
  - canonical
  - canonical/prettier
```
tried following settings but was unsuccessful.
```
prettier/prettier
  32:74  error  Insert `;` 
```
